title: Sole Pera, Ph. D
subtitle: Associate Professor @ BSU
name: Sole Pera, Ph. D
logo: /images/1280px-Boise_State_"B"_logo.svg.png

## Site Structure Configuration
collections:
  pubs:
    output: true
    permalink: /pubs/:year/:path
    sort_by:  date
  news:
    output: true
    permalink: /news/:year/:path
    sort_by:  date

defaults:
  - values:
      layout: single
  - scope:
      type: pubs
    values:
      layout: single
  - scope:
      type: news
    values:
      layout: single


## Theming Configuration
remote_theme: mmistakes/minimal-mistakes@4.17.2
minimal_mistakes_skin: default

plugins:
  - jekyll-include-cache
